name: Debug 360EatGuide

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Create folders
        run: |
          mkdir -p data

      - name: Run scraper
        run: |
          python scripts/scrape.py

      - name: Upload debug pages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-pages
          path: debug_page_*.html

      - name: Upload json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restaurants-json
          path: data/restaurants_hotels.json

      - name: Commit data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add data/restaurants_hotels.json

          git diff --cached --quiet || git commit -m "Update data"

          git push
